### PR TITLE
Bugfix/20160726 indexing task error

### PR DESCRIPTION
**Pull request by ymkjp**
I tried model indexing task as below

```sh
rake redis_search:index:model CLASS='Keyword' --trace
```

and got

<details>
 <summary>`NameError: undefined local variable or method 'item' for #<Class:0x007f8d693fe320>`</summary>
```
** Invoke redis_search:index:model (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redis_search:index:model
Redis-Search index data to Redis from [Keyword]
..................................................................................................................................................................................................................................................................................rake aborted!
NameError: undefined local variable or method `item' for #<Class:0x007feb931cf8a0>
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-search-1.0.2/lib/redis-search/base.rb:155:in `block in redis_search_index_batch_create'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/querying.rb:9:in `find_in_batches'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-search-1.0.2/lib/redis-search/base.rb:153:in `redis_search_index_batch_create'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/redis-search-1.0.2/lib/redis-search/tasks.rb:38:in `block (3 levels) in <top (required)>'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `call'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:240:in `block in execute'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `each'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `each'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:106:in `block in top_level'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:78:in `block in run'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/var/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
./bin/rake:8:in `<main>'
Tasks: TOP => redis_search:index:model
```
</details>

### CODE REVIEW

**Comment by ymkjp** [comment]
Oops, I believe this failing isn't such serious but any helps are welcome because I'm not familiar with `Mongoid::Document`.

**Comment by ymkjp** [comment]
@huacnlee Thank you, and are you planning to release v1.0.3 ?

**Comment by huacnlee** [comment]
just released

**Comment by ymkjp** [comment]
Great, thanks :shipit:

**Pull request merged**
